title: Orizuru
description: "Making it easy to add Heroku compute power to your Salesforce Applications"

exclude:
  - README.md
  - Gemfile
  - CNAME
  - script
include:
  - _pages

collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
- scope:
      path: ""
      type: docs
  values:
      layout: default
      isDoc: true

sass:
  sass_dir: _sass
  style: compressed

theme: jekyll-theme-cayman
