title: Orizuru
description: "Making it easy to add Heroku compute power to your Salesforce Applications"

exclude:
  - README.md
  - Gemfile
  - CNAME
  - script

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

